name: Build and deploy Hugo site
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'

      - name: Build
        run: hugo --minify

        uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
        with:
          ftp_host: ftp.gapura.my.id
          ftp_username: 1ikhlash1@#..
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "/"
          dist_target_dir: "/home/oiuiprtj/my-google.eu.org/adm"
          delete: "false"
